# Generated by Django 5.1.7 on 2025-03-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name='Longueur du sépale (cm)')),
                ('sepal_width', models.FloatField(verbose_name='Largeur du sépale (cm)')),
                ('petal_length', models.FloatField(verbose_name='Longueur du pétale (cm)')),
                ('petal_width', models.FloatField(verbose_name='Largeur du pétale (cm)')),
                ('species', models.CharField(blank=True, choices=[('setosa', 'Iris setosa'), ('versicolor', 'Iris versicolor'), ('virginica', 'Iris virginica')], max_length=20, null=True, verbose_name='Espèce')),
                ('prediction_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de prédiction')),
            ],
            options={
                'verbose_name': "Caractéristique d'Iris",
                'verbose_name_plural': "Caractéristiques d'Iris",
            },
        ),
    ]
